name: example-environment
channels:
  - conda-forge
  - defaults
dependencies:
  - r-base
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-plotly
  - r-stringr
  - r-caret
    r-Depends
    r-Suggests
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask

  
  
