name: example-environment
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - r-base
  - r-dplyr
  - r-ggplot2
  - r-reshape2
  - r-tidyverse
  - r-stringr
  - r-caret
  - r-kernlab
  - r-randomForest
  - r-ellipse

  
  
